apiVersion: v1
kind: Secret
metadata:
  name: micronotificaciones-secrets
  namespace: arquitectura
type: Opaque
data:
  twilio-account-sid: <BASE64_ENCODED_TWILIO_ACCOUNT_SID>
  twilio-auth-token: <BASE64_ENCODED_TWILIO_AUTH_TOKEN>
  twilio-from-phone-number: <BASE64_ENCODED_TWILIO_PHONE_NUMBER>
