apiVersion: apps/v1
kind: Deployment
metadata:
  name: micronotificaciones-deployment
  namespace: arquitectura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micronotificaciones
  template:
    metadata:
      labels:
        app: micronotificaciones
    spec:
      containers:
        - name: micronotificaciones
          image: localhost:5000/micronotificaciones:latest # ✔ Registry local
          ports:
            - containerPort: 8082
          env:
            - name: Sms__AccountSid
              valueFrom:
                secretKeyRef:
                  name: micronotificaciones-secrets
                  key: Sms__AccountSid

            - name: Sms__AuthToken
              valueFrom:
                secretKeyRef:
                  name: micronotificaciones-secrets
                  key: Sms__AuthToken

            - name: Sms__FromPhoneNumber
              valueFrom:
                secretKeyRef:
                  name: micronotificaciones-secrets
                  key: Sms__FromPhoneNumber

            # Variables Kafka (pueden moverse al secret si deseas)
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "pkc-619z3.us-east1.gcp.confluent.cloud:9092"

            - name: KAFKA_SASL_USERNAME
              value: "ME7P3ZK2LK55QXU3"

            - name: KAFKA_SASL_PASSWORD
              value: "cflt9kdlS/TNSBD9QpT/dNAYmrABdcpUE8EmT5uqlEO+4hGfESaqyMq+3Y6l4TkA"

          resources:
            limits:
              cpu: "300m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: micronotificaciones-service
  namespace: arquitectura
spec:
  type: NodePort # ✔ Ajustado a NodePort como el resto del sistema
  selector:
    app: micronotificaciones
  ports:
    - name: http
      port: 80
      targetPort: 8082
      nodePort: 30082 # ✔ NodePort fijo (estilo microservicios previos)

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: micronotificaciones-hpa
  namespace: arquitectura
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: micronotificaciones-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
