apiVersion: apps/v1
kind: Deployment
metadata:
  name: microproductos-deployment
  namespace: arquitectura
spec:
  replicas: 3 # ← ✔ 3 PODS
  selector:
    matchLabels:
      app: microproductos
  template:
    metadata:
      labels:
        app: microproductos
    spec:
      containers:
        - name: microproductos
          image: localhost:5000/microproductos:latest # ← ✔ REGISTRY LOCAL
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          resources:
            limits:
              cpu: "300m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: microproductos-service
  namespace: arquitectura
spec:
  type: ClusterIP
  selector:
    app: microproductos
  ports:
    - name: http
      port: 80
      targetPort: 8083

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: microproductos-hpa
  namespace: arquitectura
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microproductos-deployment
  minReplicas: 3 # ← ✔ MÍNIMO 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
