apiVersion: apps/v1
kind: Deployment
metadata:
  name: presentacion-deployment
  namespace: arquitectura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: presentacion
  template:
    metadata:
      labels:
        app: presentacion
    spec:
      containers:
        - name: presentacion
          image: localhost:5000/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: presentacion-service
  namespace: arquitectura
spec:
  type: NodePort
  selector:
    app: presentacion
  ports:
    - name: http
      port: 80 # puerto del Service interno
      targetPort: 80 # puerto en el contenedor NGINX
      nodePort: 32702 # Puerto externo accesible desde el navegador

