apiVersion: apps/v1
kind: Deployment
metadata:
  name: microordenes-deployment
  labels:
    app: microordenes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microordenes
  template:
    metadata:
      labels:
        app: microordenes
    spec:
      containers:
      - name: microordenes
        image: microordenes:latest
        ports:
        - containerPort: 8089
        env:
        - name: SUPABASE_URL
          value: "jdbc:postgresql://35.184.26.172:5432/micro_ordenes"
        - name: SUPABASE_USERNAME
          value: "postgres"
        - name: SUPABASE_PASSWORD
          value: "JaveMarket/01"
        - name: MICRONVENTARIO_URL
          value: "http://microinventario-service:8081/api/inventario"
        - name: MICROPAGOS_URL
          value: "http://micropagos-service:8082/api/pagos"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8089
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8089
          initialDelaySeconds: 5
          periodSeconds: 5