apiVersion: apps/v1
kind: Deployment
metadata:
  name: microcarrito-deployment
  namespace: arquitectura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microcarrito
  template:
    metadata:
      labels:
        app: microcarrito
    spec:
      containers:
        - name: microcarrito
          image: docker.io/davidjcuadros/microcarrito:latest
          ports:
            - containerPort: 8087
          resources:
            limits:
              cpu: "300m"      # Reducir de 500m
              memory: "256Mi"  # Reducir de 512Mi
            requests:
              cpu: "50m"       # Reducir de 100-250m
              memory: "64Mi" 
