apiVersion: v1
kind: Service
metadata:
  name: microcarrito-service
  namespace: arquitectura
spec:
  type: ClusterIP
  selector:
    app: microcarrito
  ports:
    - name: http
      port: 80
      targetPort: 8087