apiVersion: v1
kind: Service
metadata:
  name: microcarrito-service
  namespace: arquitectura
spec:
  type: NodePort
  selector:
    app: microcarrito
  ports:
    - name: http
      port: 80
      targetPort: 8087
      nodePort: 30087
