apiVersion: v1
kind: Service
metadata:
  name: micronotificaciones-service
  namespace: arquitectura
spec:
  type: ClusterIP
  selector:
    app: micronotificaciones
  ports:
    - name: http
      port: 80
      targetPort: 8082