apiVersion: apps/v1
kind: Deployment
metadata:
  name: micropagos-deployment
  namespace: arquitectura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micropagos
  template:
    metadata:
      labels:
        app: micropagos
    spec:
      containers:
        - name: micropagos
          image: docker.io/davidjcuadros/micropagos:latest
          ports:
            - containerPort: 8086
          env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://35.184.26.172:5432/micro_pagos"
          - name: SPRING_DATASOURCE_USERNAME
            value: "postgres"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "JaveMarket/01"
          resources:
            limits:
              cpu: "300m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"