apiVersion: v1
kind: Service
metadata:
  name: microproductos-service
  namespace: arquitectura
spec:
  type: ClusterIP
  selector:
    app: microproductos
  ports:
    - name: http
      port: 80
      targetPort: 8083
